### ISSUE TITLE
Solving problem 500A - New Year Transportation

### ISSUE THREAD

**Issue by sagarmittal1** [sagarmittal1/codeforces-solutions#1]
Problem Link - [https://codeforces.com/problemset/problem/500/A](https://codeforces.com/problemset/problem/500/A)
Problem rating: **1000**

To make the PR make the file `Problems` folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

- [ ] Appropriate title of PR
- [ ] Making another branch with an appropriate name.
- [ ] Comment on file in the top with the link of the question

All the best. Happy contributing 👍

**Comment by Arpitgupta1014** [comment]
Hey @sagarmittal1 , Can I work on this issue.

**Comment by sagarmittal1** [comment]
Sure start working on this issue, make PR when done..

**Comment by sagarmittal1** [comment]
#3
