### ISSUE TITLE
Problem 1574C - Slay the Dragon

### ISSUE THREAD

**Issue by sagarmittal1** [sagarmittal1/codeforces-solutions#10]
Problem Link -https://codeforces.com/problemset/problem/1574/C
Problem rating: **1300**
Tag - `binary search`    `greedy`    `sortings `   `ternary search`

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

Appropriate title of PR
Making another branch with an appropriate name.
Comment on file in the top with the link of the question

**Comment by Ashish-15s** [comment]
@sagarmittal1 Can I work on it?

**Comment by rishabh-arya** [comment]
Hi there.....
I am Rishabh Arya and a participant in hacktoberfest21. I am good in competitive programming and DSA. Kindly, assign me this issue so that I can fix it.
Thank you....!!!

**Comment by sagarmittal1** [comment]
Hey @rishabh-arya, @Ashish-15s asked first so, I am assigning it to him. If he can't able to do this then you can do this. 
Happy Contributing 😃

**Comment by rishabh-arya** [comment]
Sure @sagarmittal1
Thanks for your co-operation....

**Comment by sagarmittal1** [comment]
#11
