### ISSUE TITLE
Solve 158B - Taxi

### ISSUE THREAD

**Issue by sagarmittal1** [sagarmittal1/codeforces-solutions#2]
Problem Link - https://codeforces.com/problemset/problem/158/B
Problem rating: 1100

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

- [x]  Appropriate title of PR
- [x]  Making another branch with an appropriate name.
- [x]  Comment on file in the top with the link of the question

**Comment by nishkarsh540** [comment]
Hey @sagarmittal1,  can I work on this issue?

**Comment by sagarmittal1** [comment]
Yup, start working on it. Make pull request when done

**Comment by Ashish-15s** [comment]
@nishkarsh540 Are you working on this issue?

**Comment by Ashish-15s** [comment]
@nishkarsh540  If you are not working on it ,Can I work on this issue?

**Comment by nishkarsh540** [comment]
@Ashish-15s I have solved this issue.

**Comment by Ashish-15s** [comment]
@nishkarsh540 ok, I thought you are not working on it.

**Comment by nishkarsh540** [comment]
@Ashish-15s  I have not to work on this issue?
