### ISSUE TITLE
Solve 1569B - Chess Tournamant

### ISSUE THREAD

**Issue by sagarmittal1** [sagarmittal1/codeforces-solutions#5]
Problem Link - https://codeforces.com/problemset/problem/1569/B
Problem rating: 1000

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

 Appropriate title of PR
 Making another branch with an appropriate name.
 Comment on file in the top with the link of the question

**Comment by nishkarsh540** [comment]
hey @sagarmittal1, can I work on this issue?

**Comment by sagarmittal1** [comment]
Assigning it to you. Start working on this issue

**Comment by M-Manas-s** [comment]
Can I get assigned to this? @sagarmittal1

**Comment by MohitAswani** [comment]
@sagarmittal1 please checkout my PR regarding this issue .Thank you.
