### ISSUE TITLE
Solution for 1573B - Swaps

### ISSUE THREAD

**Issue by sagarmittal1** [sagarmittal1/codeforces-solutions#8]
Problem Link - https://codeforces.com/problemset/problem/1573/B
Problem rating: 1400

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

Appropriate title of PR
Making another branch with an appropriate name.
Comment on file in the top with the link of the question

All the best. 😃

**Comment by Arpitgupta1014** [comment]
Hey @sagarmittal1 , Can I work on this issue.
