### ISSUE TITLE
Solution for 1579E2 - Array Optimization by Deque

### ISSUE THREAD

**Issue by sagarmittal1** [sagarmittal1/codeforces-solutions#9]
Problem Link -https://codeforces.com/problemset/problem/1579/E2
Problem rating: **1700**
Tag - `greedy`, `data structure`

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

Appropriate title of PR
Making another branch with an appropriate name.
Comment on file in the top with the link of the question

**Comment by Arpitgupta1014** [comment]
Hey @sagarmittal1 ,Can I work on this issue.
